In [67]:
import os
import numpy    as np
import pandas   as pd
import psycopg2 as psy
import itertools

from datetime import datetime as dt
from random   import randrange
from random   import sample
from random   import choice

In [68]:
#''' Check if file exists on path. Move existing file to ARCH. Create new input for service_dim.'''

In [69]:
# Setup script input parameters

min_obs = 5                      # minimal number of observation in output dataset
max_obs = 20                     # maximal number of observation in output dataset

obs = randrange(min_obs,max_obs) # number of observation
obs

8

In [70]:
path_to_arch = "/Users/szymonbocian/Documents/Python/Arch/service"
path_to_dir  = "/Users/szymonbocian/Documents/Python/input"
file_name    = "service_dim.csv"

now          = dt.now()
path_to_file = os.path.join(path_to_dir, file_name)

if not(os.path.exists(path_to_file) and os.path.isdir(path_to_arch)):
    raise Exception('Incorrect dir')

time_stamp = "_" + str(now)[:10]
arch_file_name = 'arch_' + file_name.replace(".csv",time_stamp + ".csv")
 
os.rename(path_to_file, os.path.join(path_to_arch, arch_file_name))

Exception: Incorrect dir

In [71]:
# connection to database and return list of column column_list
try:
    connection = psy.connect( user = "szymonbocian",
                              password = "",
                              host = "localhost",
                              port = "5432",
                              database = "dwh_call_center")

    cursor = connection.cursor()

    query = "SELECT column_name FROM INFORMATION_SCHEMA.columns WHERE table_schema = 'stg' AND table_name = 'service_dim';"
    cursor.execute(query)
    column_list = cursor.fetchall()
    
except (Exception, psy.Error) as error :
    print ("Error while connecting to PostgreSQL", error)
finally:
        if(connection):
            cursor.close()
            connection.close()

column_list = [''.join(c for c in s if c not in '(),') for s in column_list]

print(column_list)

['service_full_name_eng', 'service_full_name_pl', 'service_short_name_eng', 'service_short_name_pl', 'service_code', 'service_business_key']

In [72]:
A1 = ['Junior consultant ','Consultant ','Senior consultant ','Lead consultant ','Manager ','Contractor ']
A2 = ['information ','solution ','help ']
A3 = ['call','service','consultation','advice','connection']

B1 = ['Rozmowa ','Usługa ','Konsultancja ','Porada ','Połącznie ']
B2 = ['informacyjna ','ws rozwiązania ','ws pomocy ']
B3 = ['młodszego konsultanta','konsultanta','starszego konsultanta','głównego konsultanta','manadżera','kontraktora']

In [75]:
# Cartesian product of service name both in Polish and English

A = list()
B = list()

for i in itertools.product(A1,A2,A3):
    A.append(i)

for i in itertools.product(B1,B2,B3):
    B.append(i)

df = pd.DataFrame({
    "serviceFullNameEng" : [a[0] + a[1] + a[2] for a in A],
    "serviceFullNamePl"  : [b[0] + b[1] + b[2] for b in B]
})

df['serviceShortNameEng'] = [ i[0:4] + j[0:4].title() + k[0:4].title() for i,j,k in A]
df['serviceShortNamePl']  = [ i[0:4] + j[0:4].title() + k[0:4].title() for i,j,k in B]

df['serviceCode'] = [ i[0:6].upper() + j[0:4].upper() + k[0:4].upper() + '00' for i,j,k in A]

sfnp = ('000' + (df.serviceFullNamePl.str.len()).astype(str))
df['sfnp'] = [s[-4:] for s in sfnp]

# Create service business key
df['serviceBusinessKey'] = [ i[0:1].upper() + j[0:1].upper() + k[0:4].upper() for i,j,k in A] + df.sfnp

df = df.drop(['sfnp'], axis = 1)

df

,serviceFullNameEng,serviceFullNamePl,serviceShortNameEng,serviceShortNamePl,serviceCode,serviceBusinessKey
0,Junior consultant information call,Rozmowa informacyjna młodszego konsultanta,JuniInfoCall,RozmInfoMłod,JUNIORINFOCALL00,JICALL0042
1,Junior consultant information service,Rozmowa informacyjna konsultanta,JuniInfoServ,RozmInfoKons,JUNIORINFOSERV00,JISERV0032
2,Junior consultant information consultation,Rozmowa informacyjna starszego konsultanta,JuniInfoCons,RozmInfoStar,JUNIORINFOCONS00,JICONS0042
3,Junior consultant information advice,Rozmowa informacyjna głównego konsultanta,JuniInfoAdvi,RozmInfoGłów,JUNIORINFOADVI00,JIADVI0041
4,Junior consultant information connection,Rozmowa informacyjna manadżera,JuniInfoConn,RozmInfoMana,JUNIORINFOCONN00,JICONN0030
...,...,...,...,...,...,...
85,Contractor help call,Połącznie ws pomocy konsultanta,ContHelpCall,PołąWs PKons,CONTRAHELPCALL00,CHCALL0031
86,Contractor help service,Połącznie ws pomocy starszego konsultanta,ContHelpServ,PołąWs PStar,CONTRAHELPSERV00,CHSERV0041
87,Contractor help consultation,Połącznie ws pomocy głównego konsultanta,ContHelpCons,PołąWs PGłów,CONTRAHELPCONS00,CHCONS0040
88,Contractor help advice,Połącznie ws pomocy manadżera,ContHelpAdvi,PołąWs PMana,CONTRAHELPADVI00,CHADVI0029
89,Contractor help connection,Połącznie ws pomocy kontraktora,ContHelpConn,PołąWs PKont,CONTRAHELPCONN00,CHCONN0031

In [77]:
# Create csv file with given destination

df.columns = column_list
df = df.sample(n = obs, random_state = 123)
df.to_csv(path_to_file, index = None, header = True)