In [10]:

import pandas as pd
import numpy as np
import importlib
import time

from py_package import db_conn as db
from py_package import path_maker as pm
from random import randrange
from datetime import datetime
importlib.reload(pm)
importlib.reload(db)

In [11]:
file_path_list = ["Documents","CallCenterStaffing","Input","single_call_fact.csv"]
arch_path_list = ["Documents","CallCenterStaffing","Arch","single_call"]

path = pm.PathMaker()

path_to_file = path.create(file_path_list)
path_to_arch = path.create(arch_path_list)

if path.validate(path_to_file) and path.validate(path_to_arch):
    path.move_to_arch(path_to_file, path_to_arch)
else:
    print("No file in 'Input/'")

No file in 'Input/'

In [12]:

l_conn_dict = { 
    "user"     : "szymonbocian", \
    "password" : "", \
    "host"     : "localhost", \
    "port"     : "5432", \
    "database" : "dwh_call_center"
}
db = db.DbConn(l_conn_dict)

l_obs_dict = {
    "min" : 10000, \
    "max" : 50000
}

l_period_dict = {
    "year"  : 2019, \
    "week"  : 11, \
    "start" : "06:00:00", \
    "end"   : "22:00:00"
}

# end call after 1 hour of waiting - 60 sec x 60 min
# min 5 minutes of conversation - 60 sec x 5 min
# l_join_dict = {
#     "wait_min" : 10,   \
#     "wait_max" : 1800, \
#     "conv_min" : 300,  \
#     "conv_max" : 3600
# }

l_join_dict = {
    "wait_min" : 10,  \
    "wait_max" : 900, \
    "conv_min" : 300, \
    "conv_max" : 2400
}

l_obs = randrange(l_obs_dict["min"],l_obs_dict["max"]) # number of observation

37411

In [4]:
# Create calendar as cartesian product of date x hours from Postgres
l_query_list = []
    
l_query_list.append("""
    SELECT tm.time_key, tm.time_value, dt.date_key, dt.date_value
    FROM tech.date_dim AS dt, tech.time_dim AS tm
    WHERE dt.year_value = %(year)d AND dt.iso_week_of_year = %(week)d AND time_value >= '%(start)s' AND time_value <= '%(end)s';
    """ % l_period_dict)    

l_query_list.append("SELECT office_key, office_business_key FROM pro.office_dim;")
l_query_list.append("SELECT service_key, service_business_key FROM pro.service_dim;")

l_calendar_df = pd.DataFrame(db.run_sql(l_query_list[0]), columns = ["time_key", "time_value", "date_key", "date_value"])
l_office_df   = pd.DataFrame(db.run_sql(l_query_list[1]), columns = ["office_key", "office_business_key"])
l_service_df  = pd.DataFrame(db.run_sql(l_query_list[2]), columns = ["service_key", "service_business_key"])

In [11]:

l_single_call_df = pd.DataFrame({
    "client_business_key"     : ["SB048048025M"] * l_obs, # temporary 
    "consultant_business_key" : ["AA032048000E"] * l_obs, # temporary
    "office_business_key"     : np.random.choice(l_office_df["office_business_key"], l_obs),
    "service_business_key"    : np.random.choice(l_service_df["service_business_key"], l_obs),
    "start_join_date_key"     : l_calendar_df.date_key.sample(n = l_obs)
})

l_single_call_df = pd.merge( l_single_call_df, 
                             l_calendar_df, 
                             left_index = True, 
                             right_index = True)[["client_business_key","consultant_business_key","office_business_key","service_business_key","date_key","date_value","time_key","time_value"]]

l_single_call_df["start_join_date_value"] = pd.to_datetime(l_single_call_df["date_value"])
l_single_call_df["start_conv_date_value"] = l_single_call_df["start_join_date_value"]
l_single_call_df["end_conn_date_value"] = l_single_call_df["start_conv_date_value"]

l_single_call_df["start_join_time_value"] = pd.to_timedelta(l_single_call_df["time_value"].astype(str))

l_single_call_df["wait_time"] = [ randrange(l_join_dict["wait_min"],l_join_dict["wait_max"]) for l in l_single_call_df.index ]
l_single_call_df["wait_time"] = pd.to_timedelta(l_single_call_df["wait_time"], unit = "s")

l_single_call_df["start_conv_time_value"] = l_single_call_df["start_join_time_value"] + l_single_call_df["wait_time"]

l_single_call_df["conv_time"] = [ randrange(l_join_dict["conv_min"],l_join_dict["conv_max"]) for l in l_single_call_df.index ]
l_single_call_df["conv_time"] = pd.to_timedelta(l_single_call_df["conv_time"], unit = "s")

l_single_call_df["end_conn_time_value"] = l_single_call_df["start_conv_time_value"] + l_single_call_df["conv_time"]

# l_single_call_df["start_join_timestamp"] = l_single_call_df["start_join_date_value"] + l_single_call_df["start_join_time_value"]

l_single_call_df = l_single_call_df.drop(["date_key","date_value","time_key","time_value","wait_time","conv_time"], axis = 1)
l_single_call_df.head(10)

,client_business_key,consultant_business_key,office_business_key,service_business_key,start_join_date_value,start_conv_date_value,end_conn_date_value,start_join_time_value,start_conv_time_value,end_conn_time_value
38376,SB048048025M,AA032048000E,CALCHO0796,007ACCSETT,2019-03-06,2019-03-06,2019-03-06,09:31:22,09:47:52,10:19:41
144538,SB048048025M,AA032048000E,CALLEN0538,001BILLING,2019-03-06,2019-03-06,2019-03-06,13:44:08,13:49:54,14:11:22
283454,SB048048025M,AA032048000E,CALHIM2138,004RESERVA,2019-03-07,2019-03-07,2019-03-07,19:14:53,19:25:57,19:48:06
330361,SB048048025M,AA032048000E,CALMIC1286,CICALL0001,2019-03-07,2019-03-07,2019-03-07,21:06:34,21:12:36,21:21:08
223680,SB048048025M,AA032048000E,CALCHO0796,006ORDER00,2019-03-06,2019-03-06,2019-03-06,16:52:34,16:56:46,17:03:09
78956,SB048048025M,AA032048000E,CALLEN0538,008RESPASS,2019-03-07,2019-03-07,2019-03-07,11:07:59,11:24:24,12:16:22
27802,SB048048025M,AA032048000E,CALLEN0538,001BILLING,2019-03-09,2019-03-09,2019-03-09,09:06:11,09:28:44,10:10:35
278071,SB048048025M,AA032048000E,CALLEN0538,007ACCSETT,2019-03-07,2019-03-07,2019-03-07,19:02:04,19:05:43,19:11:02
63807,SB048048025M,AA032048000E,CALHIM2138,001BILLING,2019-03-06,2019-03-06,2019-03-06,10:31:55,10:50:39,11:03:16
99281,SB048048025M,AA032048000E,CALLEN0538,005COMPLAI,2019-03-04,2019-03-04,2019-03-04,11:56:23,12:01:20,12:30:52

In [12]:

l_single_call_df.to_csv(path.create(file_path_list), 
                        index = None, 
                        header = True)